#!/bin/bash

. tests/lib.sh

RESULTS_DIR=${RESULTS_DIR:-results}
numnodes=${2:-10}
size=${1:-1}

for i in $(seq $numnodes)
do
	nodes[$i]=$(docker run -d ipfs-node)
done

# network parameters can be adjusted here
if [ -n "$NET_SETUP" ]
then
	bash -c "$NET_SETUP"
fi

# wait for nodes to come online
# TODO: better way to do this
sleep 2

for i in $(seq $(expr $numnodes - 1))
do
	connect_nodes ${nodes[$i]} ${nodes[$numnodes]}
done

mkdir -p $RESULTS_DIR

HASH=$(addfile ${nodes[1]} $numnodes)
for i in $(seq $numnodes)
do
	catfile ${nodes[$i]} $HASH > $RESULTS_DIR/output$i &
done

# wait for all cats to complete
wait

for i in $(seq $numnodes)
do
	docker kill ${nodes[$i]}
done
