#!/bin/bash

. tests/lib.sh

ctnr1=$1
ctnr2=$2

if [ -z $ctnr1 ]
then
	echo "must specify two docker containers"
	exit 1
fi

if [ -z $ctnr2 ]
then
	echo "must specify two docker containers"
	exit 1
fi

connect_nodes $ctnr1 $ctnr2

size=$3
if [ -z $size ]
then
	size=1
fi

echo "running test with file of size $size MB"

HASH=$(addfile $ctnr1 $size)
catfile $ctnr2 $HASH

